import "./globals.css";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { Anuphan } from "next/font/google";
import { getSession } from "@/actions/auth/session";
import Refesh from "@/components/Refesh";

const nuphan = Anuphan({ subsets: ["thai"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession();

    return (
        <html lang="en">
            <body className={nuphan.className}>
                <Refesh>
                    <Header session={JSON.parse(JSON.stringify(session))} />
                    {children}
                </Refesh>
            </body>
        </html>
    );
}
