import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Anuphan } from "next/font/google";

const nuphan = Anuphan({ subsets: ["thai"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={nuphan.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
